### ISSUE TITLE
Extract genes [E::main] Error: extracting genes failed.

### ISSUE THREAD

**Issue by franciscozorrilla** [AlessioMilanese/classify-genomes#5]
Hi Alessio, awesome tool thanks for sharing!

I was wondering if it would be easy/possible to modify such that I can avoid getting the error:

```
Extract genes
[E::main] Error: extracting genes failed.
```

And instead just print a warning?

I have 137 samples, with 20-80 bins per sample. I want to run one cluster job per sample, and run a loop to classify each bin. For whatever reason some bins seem to fail, showing the error message above, and the whole job quits. Therefore it would be very useful for me if the tool just tells me that the bin doesn't have enough MGs, and instead of erroring out it keeps going through the rest of the bins. 

Let me know if you have any alternative solutions for me!

Thanks,
Francisco

**Comment by AlessioMilanese** [comment]
Hi Francisco,

Thanks for using the tool!

The error `[E::main] Error: extracting genes failed.` is raised when it is not possible to extract genes from the entire fasta file. Do you have a fasta file for every bin?

> Therefore it would be very useful for me if the tool just tells me that the bin doesn't have enough MGs, and instead of erroring out it keeps going through the rest of the bins.
That would not be correct, it's not true that there are no genes. There is an error during extraction of the genes.

There are 2 solutions:
1) check why the gene extraction fails, maybe you can send me the fasta file that is causing the error?
2) when I raise an error, the python script returns a 1 (with the call `sys.exit(1)`), in your script you would have to say to continue even if there is an error.

**Comment by franciscozorrilla** [comment]
Hey Alessio,

Yes I do have a fasta file for every bin/MAG.

Here is my Snakefile rule, hope it is understandable (the {ref} wildcard contains sample names):

```

rule classifyMotus2:
    input:
        bins="/c3se/NOBACKUP/users/zorrilla/binning/metabolismPipe/bins_organized/{ref}",
        script="/c3se/users/zorrilla/Vera/temp/classify-genomes"
    output:
        "classify-motus2/{ref}"
    message:
        """
        Run classify-genome on each MAG: https://github.com/AlessioMilanese/classify-genomes
        Requires /bins_filtered/ folder to be organized in subdirectories for each sample.
        """
    shell:
        """
        set +u;source activate concoct_env;set -u
        cd {config[paths][concoct_run]}
        mkdir -p classify-motus2/$(basename {output})
        cd $TMPDIR
        cp -r {input.bins}/* .
        cp -r {input.script}/* .
        for bin in ERR*.fa; do
            echo "RUNNING BIN $bin"
            $PWD/classify-genomes $bin -t 16 -o $(echo $bin|sed 's/.fa/.taxonomy/')
            cp *.taxonomy /c3se/NOBACKUP/users/zorrilla/binning/perSamplePipe/classify-motus2/$(basename {output})
            rm *.taxonomy
            rm $bin
        done
        cd {config[paths][concoct_run]}
        """

```

Could you suggest how I could modify my rule to keep going even if the for loop throws an error? I have not been able to figure out how to do this..

For one particular job:

```
[Thu May  2 15:05:05 2019] Building DAG of jobs...
[Thu May  2 15:05:05 2019] Using shell: /usr/bin/bash
[Thu May  2 15:05:05 2019] Provided cores: 16
[Thu May  2 15:05:05 2019] Rules claiming more threads will be scaled down.
[Thu May  2 15:05:05 2019] Job counts:
[Thu May  2 15:05:05 2019] 	count	jobs
[Thu May  2 15:05:05 2019] 	1	classifyMotus2
[Thu May  2 15:05:05 2019] 	1

[Thu May  2 15:05:05 2019] Job 0: 
[Thu May  2 15:05:05 2019]         Run classify-genome on each MAG: https://github.com/AlessioMilanese/classify-genomes
[Thu May  2 15:05:05 2019]         Requires /bins_filtered/ folder to be organized in subdirectories for each sample.
[Thu May  2 15:05:05 2019]         

RUNNING BIN ERR260137_128.fa
Extract genes
Map genes to mOTUs database
Find taxonomy
RUNNING BIN ERR260137_130.fa
Extract genes
Map genes to mOTUs database
Find taxonomy
RUNNING BIN ERR260137_146.fa
Extract genes
Map genes to mOTUs database
Find taxonomy
RUNNING BIN ERR260137_148.fa
Extract genes
Map genes to mOTUs database
Find taxonomy
RUNNING BIN ERR260137_168.fa
Extract genes
Map genes to mOTUs database
Find taxonomy
RUNNING BIN ERR260137_187.fa
Extract genes
Map genes to mOTUs database
Find taxonomy
RUNNING BIN ERR260137_19.fa
Extract genes
Map genes to mOTUs database
Find taxonomy
RUNNING BIN ERR260137_204.fa
Extract genes
Map genes to mOTUs database
Find taxonomy
RUNNING BIN ERR260137_218.fa
Extract genes
Map genes to mOTUs database
Find taxonomy
RUNNING BIN ERR260137_265.fa
Extract genes
Map genes to mOTUs database
Find taxonomy
RUNNING BIN ERR260137_268.fa
Extract genes
Map genes to mOTUs database
Find taxonomy
RUNNING BIN ERR260137_278.fa
Extract genes
[E::main] Error: extracting genes failed.
[Thu May  2 15:14:47 2019] Error in rule classifyMotus2:
[Thu May  2 15:14:47 2019]     jobid: 0
[Thu May  2 15:14:47 2019]     output: classify-motus2/ERR260137
```

Here is the misbehaving fasta file:

[ERR260137_278.fa.txt](https://github.com/AlessioMilanese/classify-genomes/files/3138968/ERR260137_278.fa.txt)

I suspected it would be one of the smallest/incomplete bins causing the issue, but this particular bin is the largest in filesize from that particular sample! Perhaps it is highly contaminated?

I also tried running this bin by itself, on verbose mode:

```
python temp/classify-genomes/classify-genomes /c3se/NOBACKUP/users/zorrilla/binning/metabolismPipe/bins_organized/ERR260137/ERR260137_278.fa -t 16 -o ERR260137_278TEST.fa -v 5

Extract genes
call: python /c3se/users/zorrilla/Vera/temp/classify-genomes/makePaddedMG.py /c3se/NOBACKUP/users/zorrilla/binning/metabolismPipe/bins_organized/ERR260137/ERR260137_278.fa /tmp/tmp6_IMBK/tmp1 tmp2 --OGType mOTU --padLength 0 --numThreads 16
prodigal -a /tmp/tmp6_IMBK/tmp1/tmp2.all.proteins.fasta -d /tmp/tmp6_IMBK/tmp1/tmp2.all.genes.fasta -f gff -o /tmp/tmp6_IMBK/tmp1/tmp2.all.genes.gff -c -q -m  -p meta -i /c3se/NOBACKUP/users/zorrilla/binning/metabolismPipe/bins_organized/ERR260137/ERR260137_278.fa
perl /c3se/users/zorrilla/Vera/temp/classify-genomes/fetchMG.pl -m extraction -t 16 -o /tmp/tmp6_IMBK/tmp1/tmp2_markerGenes -d /tmp/tmp6_IMBK/tmp1/tmp2.all.genes.fasta /tmp/tmp6_IMBK/tmp1/tmp2.all.proteins.fasta

===================================================================================
         FetchMGs v1.0 - extraction of marker genes from protein sequences
          Copyright (c) 2012 Shinichi Sunagawa, Daniel R Mende, and EMBL
===================================================================================

Parsing cutoffs... done
Running HMMsearch... done
Processing results...
4791 entries from file /tmp/tmp6_IMBK/tmp1/tmp2.all.proteins.fasta were indexed in file /tmp/tmp6_IMBK/tmp1/tmp2.all.proteins.fasta.cidx
4791 entries from file /tmp/tmp6_IMBK/tmp1/tmp2.all.genes.fasta were indexed in file /tmp/tmp6_IMBK/tmp1/tmp2.all.genes.fasta.cidx
Processing completed!

Extracted sequences are saved in the directory: /tmp/tmp6_IMBK/tmp1/tmp2_markerGenes
No genes provided for extraction, provide parameter 'XXX=all' to extract all padded sequences for all genes.
[E::main] Error: extracting genes failed.
```

Any idea how I can fix this?

Thanks for the help!
Best wishes,
Francisco

**Comment by AlessioMilanese** [comment]
Hi Francisco,

Thanks for the detailed description of the error.
I have resolved the bug, can you please pull the latest version from github and try again?
There is no need to change the snakemake file.

Cheers,
alessio

**Comment by franciscozorrilla** [comment]
Hey Alessio,

Thanks for fixing the bug, I tested with the problematic fasta file and now it runs without throwing an error.
However, when I look at the output it looks like no MGs get mapped to my MAG:

```
~/temp/classify-genomes/classify-genomes /c3se/NOBACKUP/users/zorrilla/binning/metabolismPipe/bins_organized/ERR260137/ERR260137_278.fa -t 16 -o ERR260137_278.taxonomy -v 5
Extract genes
call: python /c3se/users/zorrilla/Vera/temp/classify-genomes/makePaddedMG.py /c3se/NOBACKUP/users/zorrilla/binning/metabolismPipe/bins_organized/ERR260137/ERR260137_278.fa /tmp/tmpYs9oe9/tmp1 tmp2 --padLength 0 --numThreads 16
prodigal -a /tmp/tmpYs9oe9/tmp1/tmp2.all.proteins.fasta -d /tmp/tmpYs9oe9/tmp1/tmp2.all.genes.fasta -f gff -o /tmp/tmpYs9oe9/tmp1/tmp2.all.genes.gff -c -q -m  -p meta -i /c3se/NOBACKUP/users/zorrilla/binning/metabolismPipe/bins_organized/ERR260137/ERR260137_278.fa
perl /c3se/users/zorrilla/Vera/temp/classify-genomes/fetchMG.pl -m extraction -t 16 -o /tmp/tmpYs9oe9/tmp1/tmp2_markerGenes -d /tmp/tmpYs9oe9/tmp1/tmp2.all.genes.fasta /tmp/tmpYs9oe9/tmp1/tmp2.all.proteins.fasta

===================================================================================
         FetchMGs v1.0 - extraction of marker genes from protein sequences
          Copyright (c) 2012 Shinichi Sunagawa, Daniel R Mende, and EMBL
===================================================================================

Parsing cutoffs... done
Running HMMsearch... done
Processing results...
4791 entries from file /tmp/tmpYs9oe9/tmp1/tmp2.all.proteins.fasta were indexed in file /tmp/tmpYs9oe9/tmp1/tmp2.all.proteins.fasta.cidx
4791 entries from file /tmp/tmpYs9oe9/tmp1/tmp2.all.genes.fasta were indexed in file /tmp/tmpYs9oe9/tmp1/tmp2.all.genes.fasta.cidx
Processing completed!

Extracted sequences are saved in the directory: /tmp/tmpYs9oe9/tmp1/tmp2_markerGenes
temp file with genes: /tmp/tmphDHoZx

founded_genes:
COG0541: 0
COG0016: 0
COG0495: 0
COG0533: 0
COG0215: 0
COG0012: 0
COG0525: 0
COG0552: 0
COG0172: 0
COG0018: 0
```

Output file:

```
Fasta sequence: ERR260137_278.fa
Consensus NCBI ID: NA
Consensus taxonomy: NA
Consensus mOTUs: NA
Number of detected genes: 0
Number of mapped genes: 0
Number of genes that map to -1: 0
Percentage of agreeing genes: 0%

Gene annotation:

```

Did you obtain this same result? 
I am slightly suspicious, considering this MAG was the largest in file size for this particular sample, and most other MAGs were classified successfully in that sample. However this could just be coincidental/insignificant.

I had previously run these MAGs through kraken2/bracken, so I took a look at the result I obtained for the taxonomy of this problematic bin, and it turns out the taxonomy with the highest read abundance in that bin was Homo sapiens:

```
name	taxonomy_id	taxonomy_lvl	kraken_assigned_reads	added_reads	new_est_reads	fraction_total_reads
Homo sapiens	9606	S	81	13	94	0.09845
```

So perhaps this is a contaminated bin consisting of mostly human reads. If I understand correctly, mOTUs wouldnt be able to identify a human genome/MAG correct?

Thanks!
Best wishes,
Francisco

**Comment by AlessioMilanese** [comment]
Hi Francisco,

> Did you obtain this same result?
I am slightly suspicious, considering this MAG was the largest in file size for this particular sample, and most other MAGs were classified successfully in that sample. However this could just be coincidental/insignificant.

Yes I got the same result. There are some marker genes, but none belonging to the 10 MGs.

> So perhaps this is a contaminated bin consisting of mostly human reads. If I understand correctly, mOTUs wouldnt be able to identify a human genome/MAG correct?

That's correct. The HMM are designed to extract marker genes from Bacteria or Archaea, in theory also small or unicellular Eukaryote should not be detected.

All the best,
alessio

**Comment by franciscozorrilla** [comment]
Hey Alessio,

After closer inspection I found one last problematic bin!
I tested this in verbose mode: 

```
$ /c3se/users/zorrilla/Vera/temp/classify-genomes/classify-genomes ERR260199_108.fa -t 16 -o test.out -v 5
Extract genes
call: python /c3se/users/zorrilla/Vera/temp/classify-genomes/makePaddedMG.py ERR260199_108.fa /tmp/tmpcarQxp/tmp1 tmp2 --padLength 0 --numThreads 16
prodigal -a /tmp/tmpcarQxp/tmp1/tmp2.all.proteins.fasta -d /tmp/tmpcarQxp/tmp1/tmp2.all.genes.fasta -f gff -o /tmp/tmpcarQxp/tmp1/tmp2.all.genes.gff -c -q -m  -p meta -i ERR260199_108.fa
perl /c3se/users/zorrilla/Vera/temp/classify-genomes/fetchMG.pl -m extraction -t 16 -o /tmp/tmpcarQxp/tmp1/tmp2_markerGenes -d /tmp/tmpcarQxp/tmp1/tmp2.all.genes.fasta /tmp/tmpcarQxp/tmp1/tmp2.all.proteins.fasta

===================================================================================
         FetchMGs v1.0 - extraction of marker genes from protein sequences
          Copyright (c) 2012 Shinichi Sunagawa, Daniel R Mende, and EMBL
===================================================================================

Parsing cutoffs... done
Running HMMsearch... done
Processing results...
913 entries from file /tmp/tmpcarQxp/tmp1/tmp2.all.proteins.fasta were indexed in file /tmp/tmpcarQxp/tmp1/tmp2.all.proteins.fasta.cidx
913 entries from file /tmp/tmpcarQxp/tmp1/tmp2.all.genes.fasta were indexed in file /tmp/tmpcarQxp/tmp1/tmp2.all.genes.fasta.cidx
Processing completed!

Extracted sequences are saved in the directory: /tmp/tmpcarQxp/tmp1/tmp2_markerGenes
Could not parse gene location information properly. Exiting!
[E::main] Error: extracting genes failed.
```

Any clue what is going wrong here?

[ERR260199_108.txt](https://github.com/AlessioMilanese/classify-genomes/files/3334005/ERR260199_108.txt)

Also, somewhat unrelated, could you remind me what is the meaning of "genes mapped to -1"?

Best wishes and thanks,
Francisco

**Comment by AlessioMilanese** [comment]
Hi Francisco,

Thanks for the reporting the bug!
I solved the issue, please pull the latest version.

The result should now be correct:
```
./classify-genomes ../ERR260199_108.txt
Extract genes

RESULT:
Fasta sequence: ERR260199_108.txt
Consensus NCBI ID: NA
Consensus taxonomy: NA
Consensus mOTUs: NA
Number of detected genes: 0
Number of mapped genes: 0
Number of genes that map to -1: 0
Percentage of agreeing genes: 0%

Gene annotation:
```

The issue was due to the fact that the genome that you were trying to profile had zero marker genes (out of a set of 40).

Cheers,
alessio

**Comment by franciscozorrilla** [comment]
Hi Alessio,

I have just tried installing and running classify-genomes on the EMBL cluster but I am running into some problems. I made sure all the dependencies are installed, and when I run the test case genome I get the following errors:

```
./classify-genomes AWWC01.1.fsa_nt -t 2 -v 5

Extract genes
call: python /g/scb2/patil/zorrilla/tutorial/test/makePaddedMG.py AWWC01.1.fsa_nt /tmp/tmpb3_z_gab/tmp1 tmp2 --padLength 0 --numThreads 2
prodigal -a /tmp/tmpb3_z_gab/tmp1/tmp2.all.proteins.fasta -d /tmp/tmpb3_z_gab/tmp1/tmp2.all.genes.fasta -f gff -o /tmp/tmpb3_z_gab/tmp1/tmp2.all.genes.gff -c -q -m  -p meta -i AWWC01.1.fsa_nt
perl /g/scb2/patil/zorrilla/tutorial/test/fetchMG.pl -m extraction -t 2 -o /tmp/tmpb3_z_gab/tmp1/tmp2_markerGenes -d /tmp/tmpb3_z_gab/tmp1/tmp2.all.genes.fasta /tmp/tmpb3_z_gab/tmp1/tmp2.all.proteins.fasta

===================================================================================
         FetchMGs v1.0 - extraction of marker genes from protein sequences
          Copyright (c) 2012 Shinichi Sunagawa, Daniel R Mende, and EMBL
===================================================================================

Parsing cutoffs... done
Running HMMsearch... done
Processing results...
1500 entries from file /tmp/tmpb3_z_gab/tmp1/tmp2.all.proteins.fasta were indexed in file /tmp/tmpb3_z_gab/tmp1/tmp2.all.proteins.fasta.cidx
1500 entries from file /tmp/tmpb3_z_gab/tmp1/tmp2.all.genes.fasta were indexed in file /tmp/tmpb3_z_gab/tmp1/tmp2.all.genes.fasta.cidx
Processing completed!

Extracted sequences are saved in the directory: /tmp/tmpb3_z_gab/tmp1/tmp2_markerGenes
Traceback (most recent call last):
  File "/g/scb2/patil/zorrilla/tutorial/test/makePaddedMG.py", line 444, in <module>
    status = main()
  File "/g/scb2/patil/zorrilla/tutorial/test/makePaddedMG.py", line 439, in main
    runMakePaddedMG_DB(args.contigsFasta, args.outfolder, args.runPrefix, args.gffFileName, args.contigCoordsFileName, args.contigLengthsFileName,args.padLength, args.geneNamesFileName, args.proteinFasta, transTableNumber, args.metagenomicMode, numThreads, args.OGType)
  File "/g/scb2/patil/zorrilla/tutorial/test/makePaddedMG.py", line 410, in runMakePaddedMG_DB
    getPaddedSequences(extractLocationsFileName, contigsFasta, paddedFastaFileName, dictExtractName2writeName)
  File "/g/scb2/patil/zorrilla/tutorial/test/makePaddedMG.py", line 309, in getPaddedSequences
    if (line.startswith('>')):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
[E::main] Error: extracting genes failed.
```
I get the same error when I try to run on any of my bins as well.
Not sure if this is an installation issue or perhaps there have been some changes made recently? Please let me know what you think.

Best wishes,
FZ

**Comment by AlessioMilanese** [comment]
I cannot reproduce the error.
But, I think I solved the issue in any case with commit https://github.com/AlessioMilanese/classify-genomes/commit/65c4933a82f6eb19affa2ba29a590f9f151444c8.

Please pull the latest version and let me know if it works fine.

**Comment by franciscozorrilla** [comment]
Thanks, that did the trick! 
However I had to change all indentations to spaces to avoid getting this error:

```
./classify-genomes AWWC01.1.fsa_nt -t 2 -v 5
Extract genes
call: python /g/scb2/patil/zorrilla/tutorial/scripts/classify-genomes/makePaddedMG.py AWWC01.1.fsa_nt /tmp/tmprus8946z/tmp1 tmp2 --padLength 0 --numThreads 2
  File "/g/scb2/patil/zorrilla/tutorial/scripts/classify-genomes/makePaddedMG.py", line 380
    sys.exit(0) # AFTER RUNNING FETCH_MG WE EXIT -------------- MODIFIED FOR PROGENOMES
                                                                                      ^
TabError: inconsistent use of tabs and spaces in indentation
[E::main] Error: extracting genes failed.
```

Not sure if this indentation error was because of your text editor or mine, in any case thanks again for the help!

Best,
FZ
